//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<int> Status { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
    }
}
