//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public string BranchId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Images { get; set; }
        public Nullable<int> View { get; set; }
        public string Username { get; set; }
    }
}
