//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string Id { get; set; }
        public string Username { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public string PaymentGate { get; set; }
        public string PaymentInfo { get; set; }
        public string Message { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
