//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string UserGroupId { get; set; }

        public void Copy(User user)
        {
            Name = user.Name;
            Address = user.Address;
            Birthday = user.Birthday;
            PhoneNumber = user.PhoneNumber;
            UserGroupId = user.UserGroupId;
        }
    }
}
